package interfaces;

import java.awt.BorderLayout;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import proyectossoo.CPU;
import proyectossoo.Cola;
import proyectossoo.NodoPila;
import proyectossoo.Proceso;
import org.jfree.chart.*;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Luri
 */
public class View extends javax.swing.JFrame {

    private Controlador controlador;

    public View(Controlador controlador) {
        this.controlador = controlador;

        initComponents();

    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewApp = new javax.swing.JTabbedPane();
        settings = new javax.swing.JPanel();
        cycleDurationLabel = new javax.swing.JLabel();
        planificationPolicyLabel = new javax.swing.JLabel();
        planificationPolicy = new javax.swing.JComboBox<>();
        saveSettings = new javax.swing.JButton();
        cycleDuration = new javax.swing.JSpinner();
        initSimulation = new javax.swing.JButton();
        loadSettings = new javax.swing.JButton();
        process = new javax.swing.JPanel();
        shortTimeLabel = new javax.swing.JLabel();
        shortTimePane = new javax.swing.JScrollPane();
        blocked = new javax.swing.JList<>();
        mediumTimeLabel = new javax.swing.JLabel();
        mediumTimePane = new javax.swing.JScrollPane();
        suspendedBlocked = new javax.swing.JList<>();
        suspendedReadysLabel = new javax.swing.JLabel();
        suspendedReadysPane = new javax.swing.JScrollPane();
        suspendedReadys = new javax.swing.JList<>();
        readysLabel = new javax.swing.JLabel();
        readysPane = new javax.swing.JScrollPane();
        readys = new javax.swing.JList<>();
        finishedLabel = new javax.swing.JLabel();
        finishedPane = new javax.swing.JScrollPane();
        finished = new javax.swing.JList<>();
        clockLabel = new javax.swing.JLabel();
        planPolicy = new javax.swing.JLabel();
        logPane = new javax.swing.JScrollPane();
        logList = new javax.swing.JList<>();
        runningLabel = new javax.swing.JLabel();
        PCLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        creationProcess = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nameOfProcess = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numberOfInstructions = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        boundsProcess = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cyclesOfExceptions = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        cyclesOfSatisfaction = new javax.swing.JSpinner();
        createBottom = new javax.swing.JButton();
        graphs = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        throughputPane = new javax.swing.JPanel();
        utilizacionProcesadorPane = new javax.swing.JPanel();
        tiempoRespuestaPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cycleDurationLabel.setText("Duración del ciclo en segundos");

        planificationPolicyLabel.setText("Política de planificación");

        planificationPolicy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "Round Robin", "SPN", "SRT", "HRRN", "Realimentación" }));
        planificationPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planificationPolicyActionPerformed(evt);
            }
        });

        saveSettings.setText("Guardar configuración");
        saveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettingsActionPerformed(evt);
            }
        });

        cycleDuration.setModel(new javax.swing.SpinnerNumberModel(1L, 1L, null, 1L));

        initSimulation.setText("Iniciar simulación");
        initSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initSimulationActionPerformed(evt);
            }
        });

        loadSettings.setText("Cargar configuración de CSV");
        loadSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(settingsLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cycleDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cycleDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(planificationPolicy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(planificationPolicyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(settingsLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(loadSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(initSimulation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        settingsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cycleDuration, planificationPolicy});

        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planificationPolicyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cycleDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cycleDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planificationPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initSimulation, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        settingsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cycleDuration, planificationPolicy});

        viewApp.addTab("Configuración", settings);

        shortTimeLabel.setText("Bloqueados");

        blocked.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        blocked.setVisibleRowCount(0);
        shortTimePane.setViewportView(blocked);

        mediumTimeLabel.setText("Bloq suspendidos");

        suspendedBlocked.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        suspendedBlocked.setVisibleRowCount(0);
        mediumTimePane.setViewportView(suspendedBlocked);

        suspendedReadysLabel.setText("Listos suspendidos");

        suspendedReadys.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        suspendedReadys.setVisibleRowCount(0);
        suspendedReadysPane.setViewportView(suspendedReadys);

        readysLabel.setText("Listos");

        readys.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        readys.setVisibleRowCount(0);
        readysPane.setViewportView(readys);

        finishedLabel.setText("Terminados");

        finished.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        finished.setVerifyInputWhenFocusTarget(false);
        finished.setVisibleRowCount(0);
        finishedPane.setViewportView(finished);

        clockLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockLabel.setText("CLOCK");
        clockLabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));

        planPolicy.setText("Política de planificación: ");

        logList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        logList.setToolTipText("");
        logList.setVisibleRowCount(0);
        logPane.setViewportView(logList);

        runningLabel.setForeground(java.awt.Color.black);
        runningLabel.setText("Proceso corriendo");
        runningLabel.setBorder(new javax.swing.border.MatteBorder(null));

        PCLabel.setForeground(java.awt.Color.black);
        PCLabel.setText("Proceso corriendo");
        PCLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PCLabel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout processLayout = new javax.swing.GroupLayout(process);
        process.setLayout(processLayout);
        processLayout.setHorizontalGroup(
            processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(processLayout.createSequentialGroup()
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(runningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logPane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PCLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(processLayout.createSequentialGroup()
                                .addComponent(readysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suspendedReadysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(processLayout.createSequentialGroup()
                                .addComponent(readysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suspendedReadysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(shortTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mediumTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(processLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(processLayout.createSequentialGroup()
                                .addComponent(shortTimePane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mediumTimePane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finishedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45))
        );

        processLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {finishedPane, logPane, mediumTimePane, readysPane, runningLabel, shortTimePane, suspendedReadysPane});

        processLayout.setVerticalGroup(
            processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planPolicy))
                .addGap(28, 28, 28)
                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(processLayout.createSequentialGroup()
                        .addComponent(runningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PCLabel)
                        .addGap(18, 18, 18)
                        .addComponent(logPane))
                    .addGroup(processLayout.createSequentialGroup()
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(readysLabel)
                            .addComponent(suspendedReadysLabel)
                            .addComponent(shortTimeLabel)
                            .addComponent(mediumTimeLabel)
                            .addComponent(finishedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(readysPane)
                            .addComponent(suspendedReadysPane)
                            .addComponent(shortTimePane)
                            .addComponent(mediumTimePane)
                            .addComponent(finishedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        viewApp.addTab("Procesos", process);

        jLabel8.setText("Nombre del proceso");

        nameOfProcess.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameOfProcessFocusGained(evt);
            }
        });
        nameOfProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOfProcessActionPerformed(evt);
            }
        });

        jLabel9.setText("Cantidad de instrucciones");

        numberOfInstructions.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel10.setText("CPU bound ó I/O bound");

        boundsProcess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU Bound", "I/O Bound" }));
        boundsProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boundsProcessActionPerformed(evt);
            }
        });

        jLabel11.setText("# ciclos para generar una excepción");

        cyclesOfExceptions.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cyclesOfExceptions.setEnabled(false);

        jLabel12.setText("# ciclos para satisfacer una excepción");

        cyclesOfSatisfaction.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cyclesOfSatisfaction.setEnabled(false);

        createBottom.setText("CREAR");
        createBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBottomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creationProcessLayout = new javax.swing.GroupLayout(creationProcess);
        creationProcess.setLayout(creationProcessLayout);
        creationProcessLayout.setHorizontalGroup(
            creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationProcessLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creationProcessLayout.createSequentialGroup()
                        .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creationProcessLayout.createSequentialGroup()
                                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(creationProcessLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameOfProcess))
                                    .addGroup(creationProcessLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(numberOfInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 123, Short.MAX_VALUE))))
                            .addGroup(creationProcessLayout.createSequentialGroup()
                                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cyclesOfExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boundsProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationProcessLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createBottom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationProcessLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cyclesOfSatisfaction, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(297, 297, 297))
        );

        creationProcessLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boundsProcess, cyclesOfExceptions, cyclesOfSatisfaction, numberOfInstructions});

        creationProcessLayout.setVerticalGroup(
            creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationProcessLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameOfProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(numberOfInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(boundsProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cyclesOfExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cyclesOfSatisfaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(createBottom)
                .addGap(140, 140, 140))
        );

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel8, nameOfProcess});

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel9, numberOfInstructions});

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {boundsProcess, jLabel10});

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cyclesOfExceptions, jLabel11});

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cyclesOfSatisfaction, jLabel12});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(creationProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creationProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        viewApp.addTab("Creación de procesos", jPanel1);

        javax.swing.GroupLayout throughputPaneLayout = new javax.swing.GroupLayout(throughputPane);
        throughputPane.setLayout(throughputPaneLayout);
        throughputPaneLayout.setHorizontalGroup(
            throughputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        throughputPaneLayout.setVerticalGroup(
            throughputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Throughput", throughputPane);

        javax.swing.GroupLayout utilizacionProcesadorPaneLayout = new javax.swing.GroupLayout(utilizacionProcesadorPane);
        utilizacionProcesadorPane.setLayout(utilizacionProcesadorPaneLayout);
        utilizacionProcesadorPaneLayout.setHorizontalGroup(
            utilizacionProcesadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        utilizacionProcesadorPaneLayout.setVerticalGroup(
            utilizacionProcesadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Utilización del procesador", utilizacionProcesadorPane);

        javax.swing.GroupLayout tiempoRespuestaPaneLayout = new javax.swing.GroupLayout(tiempoRespuestaPane);
        tiempoRespuestaPane.setLayout(tiempoRespuestaPaneLayout);
        tiempoRespuestaPaneLayout.setHorizontalGroup(
            tiempoRespuestaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tiempoRespuestaPaneLayout.setVerticalGroup(
            tiempoRespuestaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tiempo de respuesta", tiempoRespuestaPane);

        javax.swing.GroupLayout graphsLayout = new javax.swing.GroupLayout(graphs);
        graphs.setLayout(graphsLayout);
        graphsLayout.setHorizontalGroup(
            graphsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphsLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );
        graphsLayout.setVerticalGroup(
            graphsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphsLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        viewApp.addTab("Gráficos", graphs);

        getContentPane().add(viewApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSettingsActionPerformed
        // TODO add your handling code here:
        controlador.getCpu().guardarDatos((Long) getCycleDuration().getValue());
        controlador.getCpu().getLogList().apilar(new NodoPila("Se ha guardado las configuraciones en el archivo 'configuraciones.csv'"));
    }//GEN-LAST:event_saveSettingsActionPerformed

    private void planificationPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planificationPolicyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planificationPolicyActionPerformed

    private void createBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBottomActionPerformed

        boolean valido = true;

        if ("I/O Bound".equals((String) boundsProcess.getSelectedItem())) {
            // Verifica que un proceso I/O Bound tenga cuantos ciclos necesita para una excepcion
            if ((Integer) cyclesOfExceptions.getValue() <= 0) {
                JOptionPane.showMessageDialog(
                        null,
                        "Es necesario el número de ciclos para que se genere una excepción en un proceso I/O Bound",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
                valido = false;
            }
            // Verifica que un proceso I/O Bound tenga cuantos ciclos necesita para satisfacer una excepcion
            if ((Integer) cyclesOfSatisfaction.getValue() <= 0) {
                JOptionPane.showMessageDialog(
                        null,
                        "Es necesario el número de ciclos para que se genere una excepción en un proceso I/O Bound",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
                valido = false;
            }
            // Verifica que el numero de instrucciones sea mayor que el numero de ciclos que necesita para una excepcion
            if ((Integer) numberOfInstructions.getValue() < (Integer) cyclesOfExceptions.getValue()) {
                JOptionPane.showMessageDialog(
                        null,
                        "El numero de instrucciones debe ser mayor que el numero de ciclos para que se genere una excepcion",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
                valido = false;
            }
        }

        //Crea el nuevo proceso por parte del usuario
        if (valido == true) {
            String nameNewProcess = nameOfProcess.getText();
            int instructionsNewProcess = (Integer) numberOfInstructions.getValue();
            String boundNewProcess = (String) boundsProcess.getSelectedItem();
            int cicloex = (Integer) cyclesOfExceptions.getValue();
            int ciclofinex = (Integer) cyclesOfSatisfaction.getValue();

            Proceso newProcess = new Proceso(nameNewProcess, instructionsNewProcess, boundNewProcess, cicloex, ciclofinex);

            controlador.getCpu().getSch().agregar_listo(newProcess);
            controlador.getCpu().getLogList().apilar(new NodoPila(newProcess.getPCBLog()));

            System.out.println(newProcess.getNombre());
        }
    }//GEN-LAST:event_createBottomActionPerformed

    private void boundsProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundsProcessActionPerformed

        //Si no es I/O Bound no permite la configuracion de ciclos de excepcion y ciclos de sastifaccion
        if ("CPU Bound".equals((String) boundsProcess.getSelectedItem())) {
            cyclesOfExceptions.setValue(0);
            cyclesOfExceptions.setEnabled(false);
            cyclesOfSatisfaction.setValue(0);
            cyclesOfSatisfaction.setEnabled(false);
        } else {
            cyclesOfExceptions.setEnabled(true);
            cyclesOfExceptions.setValue(1);
            cyclesOfSatisfaction.setEnabled(true);
            cyclesOfSatisfaction.setValue(1);
        }
    }//GEN-LAST:event_boundsProcessActionPerformed

    private void nameOfProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOfProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfProcessActionPerformed

    private void nameOfProcessFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameOfProcessFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfProcessFocusGained

    public ChartPanel crearGraficoLineasThroughput() {
        JFreeChart chart = ChartFactory.createXYLineChart(
                "Throughput",
                "Ciclo",
                "Proceso/seg",
                controlador.getDatasetThroughput()
        );
        return new ChartPanel(chart);
    }

    public ChartPanel crearGraficoLineasCPU() {
        JFreeChart chart = ChartFactory.createXYLineChart(
                "Utilización del Procesador",
                "Ciclo",
                "%",
                controlador.getDatasetCPU()
        );
        return new ChartPanel(chart);
    }

    public ChartPanel crearGraficoLineasRespuesta() {
        JFreeChart chart = ChartFactory.createXYLineChart(
                "Tiempo de Respuesta",
                "Ciclo",
                "ms",
                controlador.getDatasetRespuesta()
        );
        return new ChartPanel(chart);
    }


    private void initSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initSimulationActionPerformed
        // TODO add your handling code here:
        controlador.getCpu().getLogList().apilar(new NodoPila("Iniciando simulación"));
        Thread t2 = new Thread(controlador.getCpu());
        Thread t3 = new Thread(controlador.getCpu().getSch());
        t2.start();
        t3.start();

        //Grafica throughput
        getThroughputPane().removeAll(); // Limpia el panel
        getThroughputPane().setLayout(new BorderLayout());
        getThroughputPane().add(crearGraficoLineasThroughput(), BorderLayout.CENTER);
        getThroughputPane().revalidate();
        getThroughputPane().repaint();

        //Grafica utilizacion del procesador
        getUtilizacionProcesadorPane().removeAll();
        getUtilizacionProcesadorPane().setLayout(new BorderLayout());
        getUtilizacionProcesadorPane().add(crearGraficoLineasCPU(), BorderLayout.CENTER);
        getUtilizacionProcesadorPane().revalidate();
        getUtilizacionProcesadorPane().repaint();

        //Grafica tiempo de respuesta
        getTiempoRespuestaPane().removeAll();
        getTiempoRespuestaPane().setLayout(new BorderLayout());
        getTiempoRespuestaPane().add(crearGraficoLineasRespuesta(), BorderLayout.CENTER);
        getTiempoRespuestaPane().revalidate();
        getTiempoRespuestaPane().repaint();


    }//GEN-LAST:event_initSimulationActionPerformed

    private void loadSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSettingsActionPerformed
        // TODO add your handling code here:
        getCycleDuration().setValue(controlador.getCpu().leerDatos());
        controlador.getCpu().getLogList().apilar(new NodoPila("Se ha cargado las configuraciones desde archivo 'configuraciones.csv'"));
    }//GEN-LAST:event_loadSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    public JList<String> getBlocked() {
        return blocked;
    }

    public void setBlocked(JList<String> blocked) {
        this.blocked = blocked;
    }

    public JComboBox<String> getBoundsProcess() {
        return boundsProcess;
    }

    public void setBoundsProcess(JComboBox<String> boundsProcess) {
        this.boundsProcess = boundsProcess;
    }

    public JLabel getClockLabel() {
        return clockLabel;
    }

    public void setClockLabel(JLabel clockLabel) {
        this.clockLabel = clockLabel;
    }

    public JButton getCreateBottom() {
        return createBottom;
    }

    public void setCreateBottom(JButton createBottom) {
        this.createBottom = createBottom;
    }

    public JSpinner getCycleDuration() {
        return cycleDuration;
    }

    public void setCycleDuration(JSpinner cycleDuration) {
        this.cycleDuration = cycleDuration;
    }

    public JLabel getCycleDurationLabel() {
        return cycleDurationLabel;
    }

    public void setCycleDurationLabel(JLabel cycleDurationLabel) {
        this.cycleDurationLabel = cycleDurationLabel;
    }

    public JSpinner getCyclesOfExceptions() {
        return cyclesOfExceptions;
    }

    public void setCyclesOfExceptions(JSpinner cyclesOfExceptions) {
        this.cyclesOfExceptions = cyclesOfExceptions;
    }

    public JSpinner getCyclesOfSatisfaction() {
        return cyclesOfSatisfaction;
    }

    public void setCyclesOfSatisfaction(JSpinner cyclesOfSatisfaction) {
        this.cyclesOfSatisfaction = cyclesOfSatisfaction;
    }

    public JList<String> getFinished() {
        return finished;
    }

    public void setFinished(JList<String> finished) {
        this.finished = finished;
    }

    public JLabel getFinishedLabel() {
        return finishedLabel;
    }

    public void setFinishedLabel(JLabel finishedLabel) {
        this.finishedLabel = finishedLabel;
    }

    public JScrollPane getFinishedPane() {
        return finishedPane;
    }

    public void setFinishedPane(JScrollPane finishedPane) {
        this.finishedPane = finishedPane;
    }

    public JPanel getGraphs() {
        return graphs;
    }

    public void setGraphs(JPanel graphs) {
        this.graphs = graphs;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return creationProcess;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.creationProcess = jPanel2;
    }

    public JList<String> getLogList() {
        return logList;
    }

    public void setLogList(JList<String> logList) {
        this.logList = logList;
    }

    public JScrollPane getLogPane() {
        return logPane;
    }

    public void setLogPane(JScrollPane logPane) {
        this.logPane = logPane;
    }

    public JLabel getMediumTimeLabel() {
        return mediumTimeLabel;
    }

    public void setMediumTimeLabel(JLabel mediumTimeLabel) {
        this.mediumTimeLabel = mediumTimeLabel;
    }

    public JScrollPane getMediumTimePane() {
        return mediumTimePane;
    }

    public void setMediumTimePane(JScrollPane mediumTimePane) {
        this.mediumTimePane = mediumTimePane;
    }

    public JTextField getNameOfProcess() {
        return nameOfProcess;
    }

    public void setNameOfProcess(JTextField nameOfProcess) {
        this.nameOfProcess = nameOfProcess;
    }

    public JSpinner getNumberOfInstructions() {
        return numberOfInstructions;
    }

    public void setNumberOfInstructions(JSpinner numberOfInstructions) {
        this.numberOfInstructions = numberOfInstructions;
    }

    public JLabel getPlanPolicy() {
        return planPolicy;
    }

    public void setPlanPolicy(JLabel planPolicy) {
        this.planPolicy = planPolicy;
    }

    public JComboBox<String> getPlanificationPolicy() {
        return planificationPolicy;
    }

    public void setPlanificationPolicy(JComboBox<String> planificationPolicy) {
        this.planificationPolicy = planificationPolicy;
    }

    public JLabel getPlanificationPolicyLabel() {
        return planificationPolicyLabel;
    }

    public void setPlanificationPolicyLabel(JLabel planificationPolicyLabel) {
        this.planificationPolicyLabel = planificationPolicyLabel;
    }

    public JPanel getProcess() {
        return process;
    }

    public void setProcess(JPanel process) {
        this.process = process;
    }

    public JList<String> getReadys() {
        return readys;
    }

    public void setReadys(JList<String> readys) {
        this.readys = readys;
    }

    public JLabel getReadysLabel() {
        return readysLabel;
    }

    public void setReadysLabel(JLabel readysLabel) {
        this.readysLabel = readysLabel;
    }

    public JScrollPane getReadysPane() {
        return readysPane;
    }

    public void setReadysPane(JScrollPane readysPane) {
        this.readysPane = readysPane;
    }

    public JLabel getRunningLabel() {
        return runningLabel;
    }

    public void setRunningLabel(JLabel runningLabel) {
        this.runningLabel = runningLabel;
    }

    public JButton getSaveSettings() {
        return saveSettings;
    }

    public void setSaveSettings(JButton saveSettings) {
        this.saveSettings = saveSettings;
    }

    public JPanel getSettings() {
        return settings;
    }

    public void setSettings(JPanel settings) {
        this.settings = settings;
    }

    public JLabel getShortTimeLabel() {
        return shortTimeLabel;
    }

    public void setShortTimeLabel(JLabel shortTimeLabel) {
        this.shortTimeLabel = shortTimeLabel;
    }

    public JScrollPane getShortTimePane() {
        return shortTimePane;
    }

    public void setShortTimePane(JScrollPane shortTimePane) {
        this.shortTimePane = shortTimePane;
    }

    public JList<String> getSuspendedBlocked() {
        return suspendedBlocked;
    }

    public void setSuspendedBlocked(JList<String> suspendedBlocked) {
        this.suspendedBlocked = suspendedBlocked;
    }

    public JList<String> getSuspendedReadys() {
        return suspendedReadys;
    }

    public void setSuspendedReadys(JList<String> suspendedReadys) {
        this.suspendedReadys = suspendedReadys;
    }

    public JLabel getSuspendedReadysLabel() {
        return suspendedReadysLabel;
    }

    public void setSuspendedReadysLabel(JLabel suspendedReadysLabel) {
        this.suspendedReadysLabel = suspendedReadysLabel;
    }

    public JScrollPane getSuspendedReadysPane() {
        return suspendedReadysPane;
    }

    public void setSuspendedReadysPane(JScrollPane suspendedReadysPane) {
        this.suspendedReadysPane = suspendedReadysPane;
    }

    public JTabbedPane getViewApp() {
        return viewApp;
    }

    public void setViewApp(JTabbedPane viewApp) {
        this.viewApp = viewApp;
    }

    public JLabel getPCLabel() {
        return PCLabel;
    }

    public void setPCLabel(JLabel PCLabel) {
        this.PCLabel = PCLabel;
    }

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public JPanel getCreationProcess() {
        return creationProcess;
    }

    public void setCreationProcess(JPanel creationProcess) {
        this.creationProcess = creationProcess;
    }

    public JButton getInitSimulation() {
        return initSimulation;
    }

    public void setInitSimulation(JButton initSimulation) {
        this.initSimulation = initSimulation;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JButton getLoadSettings() {
        return loadSettings;
    }

    public void setLoadSettings(JButton loadSettings) {
        this.loadSettings = loadSettings;
    }

    public JPanel getThroughputPane() {
        return throughputPane;
    }

    public void setThroughputPane(JPanel throughputPane) {
        this.throughputPane = throughputPane;
    }

    public JPanel getTiempoRespuestaPane() {
        return tiempoRespuestaPane;
    }

    public void setTiempoRespuestaPane(JPanel tiempoRespuestaPane) {
        this.tiempoRespuestaPane = tiempoRespuestaPane;
    }

    public JPanel getUtilizacionProcesadorPane() {
        return utilizacionProcesadorPane;
    }

    public void setUtilizacionProcesadorPane(JPanel utilizacionProcesadorPane) {
        this.utilizacionProcesadorPane = utilizacionProcesadorPane;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PCLabel;
    private javax.swing.JList<String> blocked;
    private javax.swing.JComboBox<String> boundsProcess;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JButton createBottom;
    private javax.swing.JPanel creationProcess;
    private javax.swing.JSpinner cycleDuration;
    private javax.swing.JLabel cycleDurationLabel;
    private javax.swing.JSpinner cyclesOfExceptions;
    private javax.swing.JSpinner cyclesOfSatisfaction;
    private javax.swing.JList<String> finished;
    private javax.swing.JLabel finishedLabel;
    private javax.swing.JScrollPane finishedPane;
    private javax.swing.JPanel graphs;
    private javax.swing.JButton initSimulation;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadSettings;
    private javax.swing.JList<String> logList;
    private javax.swing.JScrollPane logPane;
    private javax.swing.JLabel mediumTimeLabel;
    private javax.swing.JScrollPane mediumTimePane;
    private javax.swing.JTextField nameOfProcess;
    private javax.swing.JSpinner numberOfInstructions;
    private javax.swing.JLabel planPolicy;
    private javax.swing.JComboBox<String> planificationPolicy;
    private javax.swing.JLabel planificationPolicyLabel;
    private javax.swing.JPanel process;
    private javax.swing.JList<String> readys;
    private javax.swing.JLabel readysLabel;
    private javax.swing.JScrollPane readysPane;
    private javax.swing.JLabel runningLabel;
    private javax.swing.JButton saveSettings;
    private javax.swing.JPanel settings;
    private javax.swing.JLabel shortTimeLabel;
    private javax.swing.JScrollPane shortTimePane;
    private javax.swing.JList<String> suspendedBlocked;
    private javax.swing.JList<String> suspendedReadys;
    private javax.swing.JLabel suspendedReadysLabel;
    private javax.swing.JScrollPane suspendedReadysPane;
    private javax.swing.JPanel throughputPane;
    private javax.swing.JPanel tiempoRespuestaPane;
    private javax.swing.JPanel utilizacionProcesadorPane;
    private javax.swing.JTabbedPane viewApp;
    // End of variables declaration//GEN-END:variables
}
