package interfaces;

import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import proyectossoo.CPU;
import proyectossoo.Cola;
import proyectossoo.NodoPila;
import proyectossoo.Proceso;

/**
 *
 * @author Luri
 */
public class View extends javax.swing.JFrame {

    private Controlador controlador;

    public View(Controlador controlador) {
        this.controlador = controlador;

        initComponents();

        //Reloj/Cronometro
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                long inicio = System.currentTimeMillis(); // Marca de tiempo inicial
                while (true) {
                    try {
                        Thread.sleep(500);
                        long ahora = System.currentTimeMillis();
                        long transcurrido = ahora - inicio;

                        // Convertimos milisegundos a horas, minutos y segundos
                        long segundos = (transcurrido / 1000);
                        long horas = (segundos / 3600);
                        long minutos = ((segundos % 3600) / 60);
                        long seg = (segundos % 60);

                        // Formateamos como HH:mm:ss
                        String tiempo = String.format("%02d:%02d:%02d", horas, minutos, seg);
                        clockLabel.setText(tiempo);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread thread = new Thread(runnable);
        thread.start();
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());

    //Vista completa
    public View() {
        initComponents();

        //Reloj/Cronometro
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                long inicio = System.currentTimeMillis(); // Marca de tiempo inicial
                while (true) {
                    try {
                        Thread.sleep(500);
                        long ahora = System.currentTimeMillis();
                        long transcurrido = ahora - inicio;

                        // Convertimos milisegundos a horas, minutos y segundos
                        long segundos = (transcurrido / 1000);
                        long horas = (segundos / 3600);
                        long minutos = ((segundos % 3600) / 60);
                        long seg = (segundos % 60);

                        // Formateamos como HH:mm:ss
                        String tiempo = String.format("%02d:%02d:%02d", horas, minutos, seg);
                        clockLabel.setText(tiempo);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread thread = new Thread(runnable);
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewApp = new javax.swing.JTabbedPane();
        process = new javax.swing.JPanel();
        shortTimeLabel = new javax.swing.JLabel();
        shortTimePane = new javax.swing.JScrollPane();
        blocked = new javax.swing.JList<>();
        mediumTimeLabel = new javax.swing.JLabel();
        mediumTimePane = new javax.swing.JScrollPane();
        suspendedBlocked = new javax.swing.JList<>();
        suspendedReadysLabel = new javax.swing.JLabel();
        suspendedReadysPane = new javax.swing.JScrollPane();
        suspendedReadys = new javax.swing.JList<>();
        readysLabel = new javax.swing.JLabel();
        readysPane = new javax.swing.JScrollPane();
        readys = new javax.swing.JList<>();
        finishedLabel = new javax.swing.JLabel();
        finishedPane = new javax.swing.JScrollPane();
        finished = new javax.swing.JList<>();
        clockLabel = new javax.swing.JLabel();
        runningPane = new javax.swing.JPanel();
        runningLabel = new javax.swing.JLabel();
        planPolicy = new javax.swing.JLabel();
        logPane = new javax.swing.JScrollPane();
        logList = new javax.swing.JList<>();
        logLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        creationProcess = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nameOfProcess = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numberOfInstructions = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        boundsProcess = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cyclesOfExceptions = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        cyclesOfSatisfaction = new javax.swing.JSpinner();
        createBottom = new javax.swing.JButton();
        settings = new javax.swing.JPanel();
        cycleDurationLabel = new javax.swing.JLabel();
        planificationPolicyLabel = new javax.swing.JLabel();
        planificationPolicy = new javax.swing.JComboBox<>();
        saveSettings = new javax.swing.JButton();
        cycleDuration = new javax.swing.JSpinner();
        graphs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shortTimeLabel.setText("Bloqueados");

        blocked.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        shortTimePane.setViewportView(blocked);

        mediumTimeLabel.setText("Bloq suspendidos");

        suspendedBlocked.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        mediumTimePane.setViewportView(suspendedBlocked);

        suspendedReadysLabel.setText("Listos suspendidos");

        suspendedReadys.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        suspendedReadysPane.setViewportView(suspendedReadys);

        readysLabel.setText("Listos");

        readys.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        readysPane.setViewportView(readys);

        finishedLabel.setText("Terminados");

        finished.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        finished.setFixedCellWidth(0);
        finished.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        finished.setVerifyInputWhenFocusTarget(false);
        finished.setVisibleRowCount(0);
        finishedPane.setViewportView(finished);

        clockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockLabel.setText("CLOCK");
        clockLabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));

        runningPane.setBackground(java.awt.Color.lightGray);

        runningLabel.setForeground(java.awt.Color.black);
        runningLabel.setText("Proceso corriendo");

        javax.swing.GroupLayout runningPaneLayout = new javax.swing.GroupLayout(runningPane);
        runningPane.setLayout(runningPaneLayout);
        runningPaneLayout.setHorizontalGroup(
            runningPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(runningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        runningPaneLayout.setVerticalGroup(
            runningPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, runningPaneLayout.createSequentialGroup()
                .addComponent(runningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        planPolicy.setText("Política de planificación: ");

        logList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        logList.setToolTipText("");
        logPane.setViewportView(logList);

        logLabel.setText("Log");

        javax.swing.GroupLayout processLayout = new javax.swing.GroupLayout(process);
        process.setLayout(processLayout);
        processLayout.setHorizontalGroup(
            processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processLayout.createSequentialGroup()
                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(processLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(processLayout.createSequentialGroup()
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(planPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(processLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logPane, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                    .addComponent(runningPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(processLayout.createSequentialGroup()
                                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suspendedReadysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(suspendedReadysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mediumTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mediumTimePane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(finishedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finishedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(processLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(readysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shortTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(processLayout.createSequentialGroup()
                                .addComponent(readysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(shortTimePane, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47))
            .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(processLayout.createSequentialGroup()
                    .addGap(329, 329, 329)
                    .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );
        processLayout.setVerticalGroup(
            processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shortTimeLabel)
                        .addComponent(readysLabel))
                    .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(processLayout.createSequentialGroup()
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(readysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shortTimePane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(processLayout.createSequentialGroup()
                                .addComponent(suspendedReadysLabel)
                                .addGap(4, 4, 4)
                                .addComponent(suspendedReadysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(processLayout.createSequentialGroup()
                                .addComponent(mediumTimeLabel)
                                .addGap(4, 4, 4)
                                .addComponent(mediumTimePane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(processLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(planPolicy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runningPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(processLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(finishedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finishedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(logPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(processLayout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(logLabel)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );

        viewApp.addTab("Procesos", process);

        jLabel8.setText("Nombre del proceso");

        nameOfProcess.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameOfProcessFocusGained(evt);
            }
        });
        nameOfProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOfProcessActionPerformed(evt);
            }
        });

        jLabel9.setText("Cantidad de instrucciones");

        numberOfInstructions.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel10.setText("CPU bound ó I/O bound");

        boundsProcess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU Bound", "I/O Bound" }));
        boundsProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boundsProcessActionPerformed(evt);
            }
        });

        jLabel11.setText("# ciclos para generar una excepción");

        cyclesOfExceptions.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cyclesOfExceptions.setEnabled(false);

        jLabel12.setText("# ciclos para satisfacer una excepción");

        cyclesOfSatisfaction.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cyclesOfSatisfaction.setEnabled(false);

        createBottom.setText("CREAR");
        createBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBottomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creationProcessLayout = new javax.swing.GroupLayout(creationProcess);
        creationProcess.setLayout(creationProcessLayout);
        creationProcessLayout.setHorizontalGroup(
            creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationProcessLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creationProcessLayout.createSequentialGroup()
                        .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creationProcessLayout.createSequentialGroup()
                                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(creationProcessLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameOfProcess))
                                    .addGroup(creationProcessLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(numberOfInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(creationProcessLayout.createSequentialGroup()
                                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cyclesOfExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boundsProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationProcessLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createBottom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationProcessLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cyclesOfSatisfaction, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(297, 297, 297))
        );

        creationProcessLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boundsProcess, cyclesOfExceptions, cyclesOfSatisfaction, numberOfInstructions});

        creationProcessLayout.setVerticalGroup(
            creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationProcessLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameOfProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(numberOfInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(boundsProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cyclesOfExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(creationProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cyclesOfSatisfaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(createBottom)
                .addGap(119, 119, 119))
        );

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel8, nameOfProcess});

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel9, numberOfInstructions});

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {boundsProcess, jLabel10});

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cyclesOfExceptions, jLabel11});

        creationProcessLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cyclesOfSatisfaction, jLabel12});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(creationProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creationProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        viewApp.addTab("Creación de procesos", jPanel1);

        cycleDurationLabel.setText("Duración del ciclo en segundos");

        planificationPolicyLabel.setText("Política de planificación");

        planificationPolicy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "Round Robin", "SPN", "SRT", "HRRN", "Realimentación" }));
        planificationPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planificationPolicyActionPerformed(evt);
            }
        });

        saveSettings.setText("Guardar configuración");
        saveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettingsActionPerformed(evt);
            }
        });

        cycleDuration.setModel(new javax.swing.SpinnerNumberModel(1L, 1L, null, 1L));

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cycleDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cycleDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planificationPolicy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planificationPolicyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(saveSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );

        settingsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cycleDuration, planificationPolicy});

        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planificationPolicyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cycleDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planificationPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cycleDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addComponent(saveSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        settingsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cycleDuration, planificationPolicy});

        viewApp.addTab("Configuración", settings);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRAFICO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));

        javax.swing.GroupLayout graphsLayout = new javax.swing.GroupLayout(graphs);
        graphs.setLayout(graphsLayout);
        graphsLayout.setHorizontalGroup(
            graphsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphsLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        graphsLayout.setVerticalGroup(
            graphsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphsLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        viewApp.addTab("Gráficos", graphs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewApp, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewApp)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveSettingsActionPerformed

    private void planificationPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planificationPolicyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planificationPolicyActionPerformed

    private void createBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBottomActionPerformed

        //Crea el nuevo proceso por parte del usuario
        if (("I/O Bound".equals((String) boundsProcess.getSelectedItem())) && ((Integer) numberOfInstructions.getValue() < (Integer) cyclesOfExceptions.getValue()) ) {
            JOptionPane.showMessageDialog(
                    null,
                    "El numero de instrucciones debe ser mayor que el numero de ciclos para que se genere una excepcion",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            String nameNewProcess = nameOfProcess.getText();
            int instructionsNewProcess = (Integer) numberOfInstructions.getValue();
            String boundNewProcess = (String) boundsProcess.getSelectedItem();
            int cicloex = (Integer) cyclesOfExceptions.getValue();
            int ciclofinex = (Integer) cyclesOfSatisfaction.getValue();

            Proceso newProcess = new Proceso(nameNewProcess, instructionsNewProcess, boundNewProcess, cicloex, ciclofinex);

            controlador.getCpu().getSch().getPlan().add(newProcess);
            controlador.getCpu().getLogList().apilar(new NodoPila(newProcess.getPCB()));

            System.out.println(newProcess.getNombre());
        }
    }//GEN-LAST:event_createBottomActionPerformed

    private void boundsProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundsProcessActionPerformed

        //Si no es I/O Bound no permite la configuracion de ciclos de excepcion y ciclos de sastifaccion
        if ("I/O Bound".equals((String) boundsProcess.getSelectedItem())) {
            cyclesOfExceptions.setEnabled(true);
            cyclesOfExceptions.setValue(1);
            cyclesOfSatisfaction.setEnabled(true);
            cyclesOfSatisfaction.setValue(1);
        } else {
            cyclesOfExceptions.setEnabled(false);
            cyclesOfExceptions.setValue(0);
            cyclesOfSatisfaction.setEnabled(false);
            cyclesOfSatisfaction.setValue(0);
        }
    }//GEN-LAST:event_boundsProcessActionPerformed

    private void nameOfProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOfProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfProcessActionPerformed

    private void nameOfProcessFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameOfProcessFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfProcessFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    public JList<String> getBlocked() {
        return blocked;
    }

    public void setBlocked(JList<String> blocked) {
        this.blocked = blocked;
    }

    public JComboBox<String> getBoundsProcess() {
        return boundsProcess;
    }

    public void setBoundsProcess(JComboBox<String> boundsProcess) {
        this.boundsProcess = boundsProcess;
    }

    public JLabel getClockLabel() {
        return clockLabel;
    }

    public void setClockLabel(JLabel clockLabel) {
        this.clockLabel = clockLabel;
    }

    public JButton getCreateBottom() {
        return createBottom;
    }

    public void setCreateBottom(JButton createBottom) {
        this.createBottom = createBottom;
    }

    public JSpinner getCycleDuration() {
        return cycleDuration;
    }

    public void setCycleDuration(JSpinner cycleDuration) {
        this.cycleDuration = cycleDuration;
    }

    public JLabel getCycleDurationLabel() {
        return cycleDurationLabel;
    }

    public void setCycleDurationLabel(JLabel cycleDurationLabel) {
        this.cycleDurationLabel = cycleDurationLabel;
    }

    public JSpinner getCyclesOfExceptions() {
        return cyclesOfExceptions;
    }

    public void setCyclesOfExceptions(JSpinner cyclesOfExceptions) {
        this.cyclesOfExceptions = cyclesOfExceptions;
    }

    public JSpinner getCyclesOfSatisfaction() {
        return cyclesOfSatisfaction;
    }

    public void setCyclesOfSatisfaction(JSpinner cyclesOfSatisfaction) {
        this.cyclesOfSatisfaction = cyclesOfSatisfaction;
    }

    public JList<String> getFinished() {
        return finished;
    }

    public void setFinished(JList<String> finished) {
        this.finished = finished;
    }

    public JLabel getFinishedLabel() {
        return finishedLabel;
    }

    public void setFinishedLabel(JLabel finishedLabel) {
        this.finishedLabel = finishedLabel;
    }

    public JScrollPane getFinishedPane() {
        return finishedPane;
    }

    public void setFinishedPane(JScrollPane finishedPane) {
        this.finishedPane = finishedPane;
    }

    public JPanel getGraphs() {
        return graphs;
    }

    public void setGraphs(JPanel graphs) {
        this.graphs = graphs;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return creationProcess;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.creationProcess = jPanel2;
    }

    public JLabel getLogLabel() {
        return logLabel;
    }

    public void setLogLabel(JLabel logLabel) {
        this.logLabel = logLabel;
    }

    public JList<String> getLogList() {
        return logList;
    }

    public void setLogList(JList<String> logList) {
        this.logList = logList;
    }

    public JScrollPane getLogPane() {
        return logPane;
    }

    public void setLogPane(JScrollPane logPane) {
        this.logPane = logPane;
    }

    public JLabel getMediumTimeLabel() {
        return mediumTimeLabel;
    }

    public void setMediumTimeLabel(JLabel mediumTimeLabel) {
        this.mediumTimeLabel = mediumTimeLabel;
    }

    public JScrollPane getMediumTimePane() {
        return mediumTimePane;
    }

    public void setMediumTimePane(JScrollPane mediumTimePane) {
        this.mediumTimePane = mediumTimePane;
    }

    public JTextField getNameOfProcess() {
        return nameOfProcess;
    }

    public void setNameOfProcess(JTextField nameOfProcess) {
        this.nameOfProcess = nameOfProcess;
    }

    public JSpinner getNumberOfInstructions() {
        return numberOfInstructions;
    }

    public void setNumberOfInstructions(JSpinner numberOfInstructions) {
        this.numberOfInstructions = numberOfInstructions;
    }

    public JLabel getPlanPolicy() {
        return planPolicy;
    }

    public void setPlanPolicy(JLabel planPolicy) {
        this.planPolicy = planPolicy;
    }

    public JComboBox<String> getPlanificationPolicy() {
        return planificationPolicy;
    }

    public void setPlanificationPolicy(JComboBox<String> planificationPolicy) {
        this.planificationPolicy = planificationPolicy;
    }

    public JLabel getPlanificationPolicyLabel() {
        return planificationPolicyLabel;
    }

    public void setPlanificationPolicyLabel(JLabel planificationPolicyLabel) {
        this.planificationPolicyLabel = planificationPolicyLabel;
    }

    public JPanel getProcess() {
        return process;
    }

    public void setProcess(JPanel process) {
        this.process = process;
    }

    public JList<String> getReadys() {
        return readys;
    }

    public void setReadys(JList<String> readys) {
        this.readys = readys;
    }

    public JLabel getReadysLabel() {
        return readysLabel;
    }

    public void setReadysLabel(JLabel readysLabel) {
        this.readysLabel = readysLabel;
    }

    public JScrollPane getReadysPane() {
        return readysPane;
    }

    public void setReadysPane(JScrollPane readysPane) {
        this.readysPane = readysPane;
    }

    public JLabel getRunningLabel() {
        return runningLabel;
    }

    public void setRunningLabel(JLabel runningLabel) {
        this.runningLabel = runningLabel;
    }

    public JPanel getRunningPane() {
        return runningPane;
    }

    public void setRunningPane(JPanel runningPane) {
        this.runningPane = runningPane;
    }

    public JButton getSaveSettings() {
        return saveSettings;
    }

    public void setSaveSettings(JButton saveSettings) {
        this.saveSettings = saveSettings;
    }

    public JPanel getSettings() {
        return settings;
    }

    public void setSettings(JPanel settings) {
        this.settings = settings;
    }

    public JLabel getShortTimeLabel() {
        return shortTimeLabel;
    }

    public void setShortTimeLabel(JLabel shortTimeLabel) {
        this.shortTimeLabel = shortTimeLabel;
    }

    public JScrollPane getShortTimePane() {
        return shortTimePane;
    }

    public void setShortTimePane(JScrollPane shortTimePane) {
        this.shortTimePane = shortTimePane;
    }

    public JList<String> getSuspendedBlocked() {
        return suspendedBlocked;
    }

    public void setSuspendedBlocked(JList<String> suspendedBlocked) {
        this.suspendedBlocked = suspendedBlocked;
    }

    public JList<String> getSuspendedReadys() {
        return suspendedReadys;
    }

    public void setSuspendedReadys(JList<String> suspendedReadys) {
        this.suspendedReadys = suspendedReadys;
    }

    public JLabel getSuspendedReadysLabel() {
        return suspendedReadysLabel;
    }

    public void setSuspendedReadysLabel(JLabel suspendedReadysLabel) {
        this.suspendedReadysLabel = suspendedReadysLabel;
    }

    public JScrollPane getSuspendedReadysPane() {
        return suspendedReadysPane;
    }

    public void setSuspendedReadysPane(JScrollPane suspendedReadysPane) {
        this.suspendedReadysPane = suspendedReadysPane;
    }

    public JTabbedPane getViewApp() {
        return viewApp;
    }

    public void setViewApp(JTabbedPane viewApp) {
        this.viewApp = viewApp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> blocked;
    private javax.swing.JComboBox<String> boundsProcess;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JButton createBottom;
    private javax.swing.JPanel creationProcess;
    private javax.swing.JSpinner cycleDuration;
    private javax.swing.JLabel cycleDurationLabel;
    private javax.swing.JSpinner cyclesOfExceptions;
    private javax.swing.JSpinner cyclesOfSatisfaction;
    private javax.swing.JList<String> finished;
    private javax.swing.JLabel finishedLabel;
    private javax.swing.JScrollPane finishedPane;
    private javax.swing.JPanel graphs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logLabel;
    private javax.swing.JList<String> logList;
    private javax.swing.JScrollPane logPane;
    private javax.swing.JLabel mediumTimeLabel;
    private javax.swing.JScrollPane mediumTimePane;
    private javax.swing.JTextField nameOfProcess;
    private javax.swing.JSpinner numberOfInstructions;
    private javax.swing.JLabel planPolicy;
    private javax.swing.JComboBox<String> planificationPolicy;
    private javax.swing.JLabel planificationPolicyLabel;
    private javax.swing.JPanel process;
    private javax.swing.JList<String> readys;
    private javax.swing.JLabel readysLabel;
    private javax.swing.JScrollPane readysPane;
    private javax.swing.JLabel runningLabel;
    private javax.swing.JPanel runningPane;
    private javax.swing.JButton saveSettings;
    private javax.swing.JPanel settings;
    private javax.swing.JLabel shortTimeLabel;
    private javax.swing.JScrollPane shortTimePane;
    private javax.swing.JList<String> suspendedBlocked;
    private javax.swing.JList<String> suspendedReadys;
    private javax.swing.JLabel suspendedReadysLabel;
    private javax.swing.JScrollPane suspendedReadysPane;
    private javax.swing.JTabbedPane viewApp;
    // End of variables declaration//GEN-END:variables
}
